### ISSUE TITLE
Exception error when launching tools

### ISSUE THREAD

**Issue by stuartm** [easyw/Manipulator#21]
I'm not able to launch the tools from the workbench, it throws an exception:

```
Thread size out of range
Manipulator WB Activated(v 1.2.7)
Running the Python command 'AlignerTools' failed:
Traceback (most recent call last):
  File "/home/<snip>/.FreeCAD/Mod/Manipulator/ManipulatorCMD.py", line 65, in Activated
    import Aligner
  File "/home/<snip>/.FreeCAD/Mod/Manipulator/Aligner.py", line 43, in <module>
    import FreeCAD, FreeCADGui, Draft, Part, DraftTools, DraftVecUtils
  File "/usr/lib64/freecad/Mod/Draft/DraftTools.py", line 44, in <module>
    from DraftGui import todo, translate, utf8_decode
  File "/usr/lib64/freecad/Mod/Draft/DraftGui.py", line 2563, in <module>
    import DraftSnap
  File "/usr/lib64/freecad/Mod/Draft/DraftSnap.py", line 36, in <module>
    import FreeCAD, FreeCADGui, math, Draft, DraftGui, DraftTrackers, DraftVecUtils, itertools
  File "/usr/lib64/freecad/Mod/Draft/DraftTrackers.py", line 38, in <module>
    from pivy import coin
  File "/usr/lib64/python3.7/site-packages/pivy/__init__.py", line 30, in <module>
    from .coin import SoDB, SoNodeKit, SoInteraction
  File "/usr/lib64/python3.7/site-packages/pivy/coin.py", line 67214, in <module>
    for x in locals().values():

dictionary changed size during iteration
```

Python 3.7 and FreeCAD 0.18

**Comment by easyw** [comment]
hi @stuartm 
would you please add your full FreeCAD information?
I don't have issue on:

> OS: Linux Mint 19.1
> Word size of OS: 64-bit
> Word size of FreeCAD: 64-bit
> Version: 0.18.3.
> Build type: Release
> Python version: 3.6.8
> Qt version: 5.9.5
> Coin version: 4.0.0a
> OCC version: 7.3.0
> Locale: English/UnitedStates (en_US)
>
