### ISSUE TITLE
Cannot align linked parts

### ISSUE THREAD

**Issue by ethanc8** [easyw/Manipulator#45]
Hello, I have a part which is linked to another file and a part which is in this file, and I'd like to align them together. However, using the Aligner Workbench results in

```
14:24:49  Align clicked
14:24:49  centering on Center of Mass
14:24:49  Centering and aligning Planes
14:24:49  position written float/589/269/302/394
14:24:49  111
14:24:49  number of objects: 2
14:24:49  obj: MS3_Stage
14:24:49  Placement: Placement [Pos=(-30.2919,0.263641,-0.038), Yaw-Pitch-Roll=(0,0,90)]
14:24:49  obj: Part__Feature
14:24:49  Placement: Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(0,0,0)]
14:24:49  j= 0
14:24:49  len selEx 2
14:24:49  Label : MS3_Stage
14:24:49  Name  : MS3_Stage
14:24:49  Center Face Binder 0 Vector (4.887070519600947, 0.26364103920189486, -4.483000000000003)
14:24:49  Center Face Binder bb 0 Vector (4.88707051960095, 0.26364103920189397, -4.483000000000003)
14:24:49  Part
14:24:49  Link001
14:24:49  Stage Assembly App::Link
14:24:49  ['Part', 'Link001']
14:24:49  Traceback (most recent call last):
14:24:49    File "/home/ethan/.local/share/FreeCAD/Mod/Manipulator/./Aligner.py", line 884, in onAlign
14:24:49      Align(normal,type,mode,cx,cy,cz)
14:24:49    File "/home/ethan/.local/share/FreeCAD/Mod/Manipulator/./Aligner.py", line 2030, in Align
14:24:49      listSorted=get_sorted_list (ob)
14:24:49                 ^^^^^^^^^^^^^^^^^^^^
14:24:49    File "/home/ethan/.local/share/FreeCAD/Mod/Manipulator/./Aligner.py", line 1510, in get_sorted_list
14:24:49      if len(ap.InListRecursive) < lvl:
14:24:49             ^^^^^^^^^^^^^^^^^^
14:24:49  AttributeError: 'NoneType' object has no attribute 'InListRecursive'
```
[assemblies-1.zip](https://github.com/user-attachments/files/16133723/assemblies-1.zip)

**Comment by ethanc8** [comment]
Specifically, I am trying to align the bottom of the "Stage Assembly" to the top of the "MB1824A" by aligning two lines on the edges of the two assemblies
