### ISSUE TITLE
Caliper crashes FreeCAD

### ISSUE THREAD

**Issue by macdroid53** [easyw/Manipulator#47]
I just attempted to use the caliper to measure an angle.

To duplicate:

- New document
- Add threaded rod from Fasteners WB (set to show threads)
- select Caliper tool
- select angle radio button
- select two seam lines between threads

It did get the angle as shown below, but then FreeCAD crashed.
Note: this is on Manjaro where FC is built with Qt6.

`FreeCAD 1.1.0, Libs: 1.1.0devR39745 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Manipulator WB Activated(v 1.5.7)
https://github.com/easyw/Manipulator-> commits:198
the WB is Up to Date
Caliper version 1.6.8
position set float/197/242/396/329
Caliper version 1.6.8
Caliper
closed
Caliper active :)
position written float/197/242/396/330
starting!
**Angle : 60.00**
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3d1d0) [0x7d69dde4c1d0]
#1  0x7d69e0ceb1a4 in App::PropertyString::getValue() const from /usr/lib/freecad/lib/libFreeCADApp.so+0x4
#2  0x7d69e19763af in Gui::DockWnd::SelectionView::onSelectionChanged(Gui::SelectionChanges const&) from /usr/lib/freecad/lib/libFreeCADGui.so+0xb6f
#3  0x7d69e1db8d30 in Gui::SelectionObserver::_onSelectionChanged(Gui::SelectionChanges const&) from /usr/lib/freecad/lib/libFreeCADGui.so+0x30
#4  0x7d69e19be1c7 in boost::signals2::detail::signal_impl<void (Gui::SelectionChanges const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (Gui::SelectionChanges const&)>, boost::function<void (boost::signals2::connection const&, Gui::SelectionChanges const&)>, boost::signals2::mutex>::operator()(Gui::SelectionChanges const&) from /usr/lib/freecad/lib/libFreeCADGui.so+0x3c7
#5  0x7d69e1dbae5f in Gui::SelectionSingleton::notify(Gui::SelectionChanges&&) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1bf
#6  0x7d69e1dbd83b in Gui::SelectionSingleton::addSelection(char const*, char const*, char const*, float, float, float, std::vector<Gui::SelectionSingleton::SelObj, std::allocator<Gui::SelectionSingleton::SelObj> > const*, bool) from /usr/lib/freecad/lib/libFreeCADGui.so+0xb6b
#7  0x7d69e1a81204 in Gui::SoFCUnifiedSelection::setSelection(std::vector<Gui::SoFCUnifiedSelection::PickedInfo, std::allocator<Gui::SoFCUnifiedSelection::PickedInfo> > const&, bool) from /usr/lib/freecad/lib/libFreeCADGui.so+0x11c4
#8  0x7d69e1a8230e in Gui::SoFCUnifiedSelection::handleEvent(SoHandleEventAction*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x14e
#9  0x7d`

**Comment by Bazmundi** [comment]
Yeop. I can confirm same problem. App closes immediately I select the second point for the angle caliper.

In fact I tore out and reinstalled FreeCAD a week ago to try to sort other issues out, so I've a fresh install with Manipulator the only additional addon I've installed yet.

OS: KDE Flatpak runtime (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.0.2.39319 (Git) Flatpak
Build type: Release
Branch: (HEAD detached at 256fc7e)
Hash: 256fc7eff3379911ab5daf88e10182c509aa8052
Python 3.12.10, Qt 6.9.0, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/Australia (en_AU)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Installed mods: 
  * Manipulator 1.6.3
